language: elixir
elixir: 1.2
otp_release:
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - mix docs